#!/bin/bash
clear
echo "Appoinment App - v1.0"
echo "                                                                          
                                                                          
                       w                                                  
   w   w   w     w    www   wwwww               www                       
   w   ww ww    ww   w  w    w    wwww  wwwww   w  ww   w                 
   ww   ww     w   wwwwwww   w    w     wwwww   w      www   w    w       
    wwww  ww ww    w     w   w    www   ww     wwww   ww w   w    w       
    ww     www     w     w   w    w     www     w    wwwwww  w    w       
                         ww        wwww w  w    w    w    w  w    w       
                                                w    w    w  www  wwww    
                                                                          
                                                                          
                                                                          
                                  w                                       
                                                                          
                       wwwwww     w                                       
                       w    ww    w                                       
                       w     w    w                                       
                       w wwww     w                                       
                       ww  www    w                                       
                       w      ww  w                                       
                       w       w  w                                       
                       w       w  w                                       
                       wwwwwwww   w                                       
                                                                          
                                                                          
                                                                          
                                                                          
                                                                          
                                                                          
"